#include "PlotterExporter.h"
#include "ofxGCode.hpp"
#include <string>

namespace plotter {

// Coordinates are already in mm — setup scale = 1.
static ofxGCode buildGCode()
{
    ofxGCode g;
    g.setup(1.0f);
    return g;
}

// Populate @p g with all polylines from @p paths.
static void addPaths(ofxGCode& g, const std::vector<ofPolyline>& paths)
{
    for (const auto& path : paths) {
        if (path.size() < 2) continue;
        std::vector<ofVec2f> pts;
        pts.reserve(path.size());
        for (const auto& v : path.getVertices()) {
            pts.push_back({v.x, v.y});
        }
        g.polygon(pts, false);
    }
}

// Build a plotter-aware G-code string from an already-populated ofxGCode
// object, respecting all PenSettings (feed rates, slow-travel mode, etc.).
static std::string buildGCodeString(ofxGCode& g, const PenSettings& pen)
{
    using std::to_string;
    const float safeZ        = pen.penUpZ;
    const float downZ        = pen.penDownZ;
    const float drawF        = pen.drawSpeed;
    const float plungeF      = pen.drawSpeed * 0.5f;
    const bool  slowTravels  = pen.slowTravels;
    const float travelF      = pen.travelSpeed;

    const std::string travelCmd = slowTravels ? "G1" : "G0";
    const std::string travelFStr = slowTravels ? (" F" + to_string((int)travelF)) : "";

    std::vector<std::string> commands;
    commands.push_back("G21 ; mm mode");
    commands.push_back("G90 ; absolute positioning");
    commands.push_back("G0 Z" + ofToString(safeZ, 3) + " ; pen up");
    commands.push_back("G0 X0 Y0 ; home");

    ofVec2f lastPos(0, 0);
    bool penIsUp   = true;
    bool firstDraw = true;

    for (const auto& line : g.lines) {
        if (line.a != lastPos || penIsUp) {
            if (!penIsUp) {
                commands.push_back("G0 Z" + ofToString(safeZ, 3) + " ; pen up");
                penIsUp = true;
            }
            commands.push_back(travelCmd
                + " X" + ofToString(line.a.x, 3)
                + " Y" + ofToString(line.a.y, 3) + travelFStr);
            commands.push_back("G1 Z" + ofToString(downZ, 3) + " F" + to_string((int)plungeF) + " ; pen down");
            penIsUp   = false;
            firstDraw = true;
        }

        std::string move = "G1 X" + ofToString(line.b.x, 3) + " Y" + ofToString(line.b.y, 3);
        if (firstDraw) { move += " F" + to_string((int)drawF); firstDraw = false; }
        commands.push_back(move);

        lastPos = line.b;
    }

    commands.push_back("G0 Z" + ofToString(safeZ, 3) + " ; pen up");
    commands.push_back("G0 X0 Y0 ; home");
    commands.push_back("M2 ; end program");

    std::string result;
    result.reserve(commands.size() * 24);
    for (const auto& cmd : commands) result += cmd + "\n";
    return result;
}

// -----------------------------------------------------------------------

std::string toGCode(const ImageToPath& engine)
{
    ofxGCode g = buildGCode();
    addPaths(g, engine.getPaths());

    std::string header;
    header += "; Generated by ofxPlotter (via ofxGCode)\n";
    header += "; Paths: "    + std::to_string(engine.totalPaths)
            + ", Distance: " + std::to_string((int)engine.totalDistance) + " mm\n";
    header += "; Estimated time: " + std::to_string((int)(engine.estimatedTime / 60)) + " min\n";
    if (engine.pen.slowTravels)
        header += "; slowTravels: G1 F" + std::to_string((int)engine.pen.travelSpeed) + "\n";
    header += "\n";

    return header + buildGCodeString(g, engine.pen);
}

std::string toGCodeForLayer(const ImageToPath& engine, int layerIdx)
{
    if (layerIdx < 0 || layerIdx >= (int)engine.layers.size()) return "";
    const auto& layer = engine.layers[layerIdx];

    ofxGCode g = buildGCode();
    addPaths(g, layer.paths);

    std::string header;
    header += "; Generated by ofxPlotter (via ofxGCode) - Layer: " + layer.name + "\n";
    header += "; Paths: "    + std::to_string(layer.totalPaths)
            + ", Distance: " + std::to_string((int)layer.totalDistance) + " mm\n";
    header += "; Estimated time: " + std::to_string((int)(layer.estimatedTime / 60)) + " min\n";
    if (engine.pen.slowTravels)
        header += "; slowTravels: G1 F" + std::to_string((int)engine.pen.travelSpeed) + "\n";
    header += "\n";

    return header + buildGCodeString(g, engine.pen);
}

} // namespace plotter
